//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baza3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKS()
        {
            this.BOOK_COPIES = new HashSet<BOOK_COPIES>();
            this.AUTHORS = new HashSet<AUTHORS>();
            this.TAGS = new HashSet<TAGS>();
        }
    
        public decimal ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<decimal> ISBN { get; set; }
        public decimal CATEGORIES_ID { get; set; }
        public decimal PUBLISHERS_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_COPIES> BOOK_COPIES { get; set; }
        public virtual CATEGORIES CATEGORIES { get; set; }
        public virtual PUBLISHERS PUBLISHERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHORS> AUTHORS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGS> TAGS { get; set; }
    }
}
