//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baza3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHORS> AUTHORS { get; set; }
        public virtual DbSet<BOOK_COPIES> BOOK_COPIES { get; set; }
        public virtual DbSet<BOOK_RENTALS> BOOK_RENTALS { get; set; }
        public virtual DbSet<BOOKS> BOOKS { get; set; }
        public virtual DbSet<CATEGORIES> CATEGORIES { get; set; }
        public virtual DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public virtual DbSet<PENALTIES> PENALTIES { get; set; }
        public virtual DbSet<PUBLISHERS> PUBLISHERS { get; set; }
        public virtual DbSet<TAGS> TAGS { get; set; }
        public virtual DbSet<TB_TEST_1> TB_TEST_1 { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<USER_FAVORITES> USER_FAVORITES { get; set; }
    }
}
