//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baza3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_FAVORITES
    {
        public Nullable<decimal> BOOK_ID { get; set; }
        public decimal USERS_ID { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
